2023-06-08 06:05:57,256 INFO    MainThread:17743 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-06-08 06:05:57,257 INFO    MainThread:17743 [wandb_setup.py:_flush():76] Configure stats pid to 17743
2023-06-08 06:05:57,257 INFO    MainThread:17743 [wandb_setup.py:_flush():76] Loading settings from /home/modf/.config/wandb/settings
2023-06-08 06:05:57,257 INFO    MainThread:17743 [wandb_setup.py:_flush():76] Loading settings from /home/modf/wnab-workshop/wandb/settings
2023-06-08 06:05:57,257 INFO    MainThread:17743 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-06-08 06:05:57,257 INFO    MainThread:17743 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-06-08 06:05:57,257 INFO    MainThread:17743 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'preprocess_data.py', 'program': '/home/modf/wnab-workshop/preprocess_data.py'}
2023-06-08 06:05:57,257 INFO    MainThread:17743 [wandb_init.py:_log_setup():507] Logging user logs to /home/modf/wnab-workshop/wandb/run-20230608_060557-6cf00z76/logs/debug.log
2023-06-08 06:05:57,257 INFO    MainThread:17743 [wandb_init.py:_log_setup():508] Logging internal logs to /home/modf/wnab-workshop/wandb/run-20230608_060557-6cf00z76/logs/debug-internal.log
2023-06-08 06:05:57,257 INFO    MainThread:17743 [wandb_init.py:init():547] calling init triggers
2023-06-08 06:05:57,257 INFO    MainThread:17743 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-06-08 06:05:57,257 INFO    MainThread:17743 [wandb_init.py:init():596] starting backend
2023-06-08 06:05:57,257 INFO    MainThread:17743 [wandb_init.py:init():600] setting up manager
2023-06-08 06:05:57,261 INFO    MainThread:17743 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-06-08 06:05:57,266 INFO    MainThread:17743 [wandb_init.py:init():606] backend started and connected
2023-06-08 06:05:57,270 INFO    MainThread:17743 [wandb_init.py:init():703] updated telemetry
2023-06-08 06:05:57,270 INFO    MainThread:17743 [wandb_init.py:init():736] communicating run to backend with 60.0 second timeout
2023-06-08 06:05:57,942 ERROR   MainThread:17743 [wandb_init.py:init():762] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2023-06-08 06:05:58,194 ERROR   MainThread:17743 [wandb_init.py:init():1170] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/home/modf/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1152, in init
    run = wi.init()
  File "/home/modf/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 768, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2023-06-08 06:05:59,222 WARNING MsgRouterThr:17743 [router.py:message_loop():77] message_loop has been closed
